name: Deploy to GitHub Pages

on:
  # 当代码推送到主分支时触发（如果你的默认分支叫 master，请把这里改成 master）
  push:
    branches: ["main"]

# 赋予 GitHub Action 部署到 Pages 的权限
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # 指向 Vite 打包生成的存放目录
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4